import Img1 from ".//Image/img1.svg";
import Img2 from "./Image/img2.svg";
import Img3 from "./Image/img3.svg";
import Img4 from "./Image/img4.png";
import Img5 from "./Image/img5.svg";
import Img6 from "./Image/img6.svg";
import Img7 from "./Image/img7.svg";
import Img8 from "./Image/img8.svg";
import Img9 from "./Image/img9.svg";
import Img10 from "./Image/img10.svg";

const data = [
  {
    id: 1,
    heading: "Spiritswap LeN",
    image1: true,
    image2: true,
    image3: true,
    image4: true,
    image5: true,
    image6: Img6,
    image7: true,
    image8: Img8,
    image9: true,
    image10: Img10,
    banana: false,
    image12: false,
    image13: false,
    image14: false,
    image15: false,
    image16: false,
    image17: false,

    decs: "TVL",
    para: "1,190,772$",
    decs1: "Chain",
    para2: "Fantom Opera",
    button: "ENTER NETWORK",
  },
  {
    id: 1,
    heading: "ApeSwap LeN",
    image1: true,
    image4: true,
    image5: true,
    banana: true,
    image12: true,
    image13: true,
    image2: true,
    image14: true,
    image15: true,
    image16: false,
    image17: false,
    image9: false,
    decs: "TVL",
    para: "30,102,267$",
    decs1: "Chain",
    para2: "BSC",
    button: "ENTER NETWORK",
    margin: "12px 0 0 0",
  },
  {
    id: 1,
    heading: "Hector LeN",
    image1: true,
    image4: true,
    image7: true,
    image16: true,
    image2: true,
    image17: true,
    image9: true,
    image18: true,
    image19: true,
    decs: "TVL",
    para: "7,514,043$",
    decs1: "Chain",
    para2: "Fantom Opera",
    button: "ENTER NETWORK",
    margin: "12px 0 0 0",
  },
  {
    id: 1,
    heading: "KnightSwap LeN",

    image4: true,
    image1: true,
    image20: true,
    image12: true,
    image2: true,
    image13: true,
    image9: true,
    image21: true,
    decs: "TVL",
    para: "7,514,043$",
    decs1: "Chain",
    para2: "BSC",
    button: "ENTER NETWORK",
    margin: "12px 0 0 0",
  },
  {
    id: 1,
    heading: "Frax LeN",
    image1: false,
    image22: true,
    image7: true,
    image2: true,
    image23: true,
    decs: "TVL",
    para: "7,514,043$",
    decs1: "Chain",
    para2: "Moonbeam",
    button: "ENTER NETWORK",
    margin: "4.4rem 0 0 0",
    padding: "0 15px",
  },
  {
    id: 1,
    heading: "OolongSwap LeN",
    image24: true,
    image4: true,
    image2: true,
    image13: true,
    image16: true,
    image7: true,
    image25: true,

    decs: "TVL",
    para: "7,514,043$",
    decs1: "Chain",
    para2: "Boba",
    button: "ENTER NETWORK",
    margin: "2.8rem 0 0 0",
    //  padding:"0 15px",
  },
  {
    id: 1,
    heading: "BeamSwap LeN",
    image26: true,
    image4: false,
    image1: false,
    image20: false,
    image12: true,
    image2: true,
    image13: false,
    image9: false,
    image21: false,
    image4: true,
    image5: true,
    image23: true,
    // image13:true,

    decs: "TVL",
    para: "7,514,043$",
    decs1: "Chain",
    para2: "Moonbeam",
    button: "ENTER NETWORK",
    margin: "5rem 0 0 0",
    //  padding:"0 15px",
    display: "flex",
    "justify-content": "center",
  },
];

export default data;
